### ISSUE TITLE
Minimum Python version on UCL's Myriad

### ISSUE THREAD

**Issue by cjlegg** [ukri-excalibur/excalibur-tests#228]
The README of this project says use Python 3.7 or later. On UCL's Myriad cluster the there recommended Python module loads Python  python3/recommended loads Python 3.9.6, but installing this project as per the README then leads to this error 

```
$ reframe -V
Traceback (most recent call last):
  File "/lustre/scratch/scratch/ucapcjg/excalibur-bm/pyenv/bin/reframe", line 19, in <module>
    import reframe.frontend.cli as cli  # noqa: F401, F403
  File "/lustre/scratch/scratch/ucapcjg/excalibur-bm/pyenv/lib/python3.9/site-packages/reframe/__init__.py", line 25, in <module>
    from reframe.core.pipeline import *     # noqa: F401, F403
  File "/lustre/scratch/scratch/ucapcjg/excalibur-bm/pyenv/lib/python3.9/site-packages/reframe/core/pipeline.py", line 26, in <module>
    import reframe.core.logging as logging
  File "/lustre/scratch/scratch/ucapcjg/excalibur-bm/pyenv/lib/python3.9/site-packages/reframe/core/logging.py", line 12, in <module>
    import requests
  File "/lustre/scratch/scratch/ucapcjg/excalibur-bm/pyenv/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/lustre/scratch/scratch/ucapcjg/excalibur-bm/pyenv/lib/python3.9/site-packages/urllib3/__init__.py", line 41, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
```
The error is fixed by using Myriad's python 3.11.4, which has a module openssl/1.1.1u as a prerequisite.

So the suggestion is to add to the README a note to use a python built with/against a minimum version of openssl.

**Comment by giordano** [comment]
The fact is that that's a moving indirect requirement from dependencies of dependencies of our framework, not something we have direct control over.  We don't require `urllib3` directly: https://github.com/ukri-excalibur/excalibur-tests/blob/637ac6d5a2d45c8b3f02de3a452428d5da8a14e8/pyproject.toml#L25-L28  Should whatever package which requires urllib3 down the stack change their requirement, whatever we write in the README would become outdated.

**Comment by tkoskela** [comment]
I'd agree with Mose that we can't control indirect dependencies. We should put a note about this for myriad in `SYSTEMS.md`
