### ISSUE TITLE
Post-processing breaks with numpy/2.0.0

### ISSUE THREAD

**Issue by tkoskela** [ukri-excalibur/excalibur-tests#334]
```
Traceback (most recent call last):
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/tkoskela/git_repos/excalibur-tests/post-processing/streamlit_post_processing.py", line 7, in <module>
    from post_processing import PostProcessing
  File "/home/tkoskela/git_repos/excalibur-tests/post-processing/post_processing.py", line 11, in <module>
    from plot_handler import plot_generic
  File "/home/tkoskela/git_repos/excalibur-tests/post-processing/plot_handler.py", line 7, in <module>
    from bokeh.models import HoverTool, Legend
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/bokeh/models/__init__.py", line 33, in <module>
    from ..core.property.dataspec import expr, field, value  # Legacy API
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/bokeh/core/property/dataspec.py", line 35, in <module>
    from .color import Color
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/bokeh/core/property/color.py", line 30, in <module>
    from .container import Tuple
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/bokeh/core/property/container.py", line 38, in <module>
    from .enum import Enum
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/bokeh/core/property/enum.py", line 27, in <module>
    from .primitive import String
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/bokeh/core/property/primitive.py", line 37, in <module>
    bokeh_bool_types += (np.bool8,)
  File "/home/tkoskela/python_envs/lexci/lib/python3.10/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'
```

**Comment by giordano** [comment]
It was fixed two years ago in bokeh 3.1.0: https://github.com/bokeh/bokeh/pull/12690
